<!doctype html><!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]--><!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]--><!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]--><!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]--><!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]--><head>	<meta charset="UTF-8">	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">		<title>Sam Wards Portfolio</title>	<meta name="description" content="">	<meta name="author" content="">		<meta name="viewport" content="width=device-width, initial-scale=1.0">		<link rel="shortcut icon" href="/favicon.ico">	<link rel="apple-touch-icon" href="/apple-touch-icon.png">	<link rel="stylesheet" href="css/style.css?v=2">	<script src="js/libs/modernizr-1.7.min.js"></script></head><body>	<div id="container">		<header>		<?php include('includes/header.php'); ?>		</header>				<?php include('includes/nav.php'); ?>		<div id="main" role="main">					<!-- <p id="intro">			Hi, I'm Sam, a programmer and developer with a passion for designing beautiful applications with elegant code. Take a look.			</p> -->						<section>
			<div id="article-container">
				<article class="with-img">
					<a href="#"> <h1>Grade Calculator</h1> </a>
						<h2>What is it?</h2>
						<p>Calculates university grades to simplify working out the classifications</p>
						<h2>Technologies Used</h2>
						<ul>
							<li>HTML</li>
							<li>CSS</li>
							<li>Javascript</li>
							<li>JQuery</li>
						</ul>
				</article>
				<img src="images/gradecalc.png">
			</div>				<div id="article-container">					<article class="with-img">						<a href="#"> <h1>This Website</h1> </a>							<h2>What is it?</h2>							<p>This is a website to store all my projects and sharpen my HTML, CSS, PHP and Javascript skills.</p>							<h2>Technologies Used</h2>							<ul>								<li>HTML</li>								<li>CSS</li>								<li>PHP</li>								<li>Javascript</li>								<li>HTML 5</li>								<li><a href="http://html5boilerplate.com">HTML5 Boilerplate</a></li>							</ul>											</article>					<img src="images/thiswebsite.png">				</div>								<div id="article-container">					<article class="with-img">						<a href="http://github.com/samst0r/Downloads-Sorter"> <h1>Downloads Cleaner</h1> </a>							<h2>What is it?</h2>							<p><a href="http://github.com/samst0r/Downloads-Sorter">Downloads Cleaner</a> is a <a href="http://www.python.org/">Python</a> script that I wrote to help keep my downloads folder organised. It sorts files in the current folder. It creates two folders, Last Week and Older.														The files and folders that are less than 24hrs old stay in the root of the folder.</p>							<h2>Technologies Used</h2>							<ul>							<li>Python</li>							<li>VIM</li>							<li>Git</li>							<li><a href="http://github.com/samst0r/Downloads-Sorter">GitHub</a></li>							</ul>											</article>					<img src="images/DownloadCleaner.png">				</div>								<div id="article-container">					<article class="with-img">						<a href="http://ukparapack.co.uk/default.aspx"> <h1>UKParaPack</h1> </a>						<h2>What is it?</h2>						<p><a href="http://ukparapack.co.uk/default.aspx">UKParaPack</a> is a port of the Medical 							Guidelines to the iPhone. The App 							allows medics to quickly look up 							important information. The backend 							uses a customised UIWebview 							capable of handling local HTML.						</p>													<h2>Technologies</h2>						<ul>							<li>Objective-C</li>							<li>HTML</li>							<li>CSS</li>							<li>Photoshop</li>						</ul>											</article>					<img src="images/ukparapack.png">				</div>						</section>		</div>				</div>	<footer>			<?php include('includes/footer.php'); ?>		</footer>	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>	<script>!window.jQuery && document.write(unescape('%3Cscript src="js/libs/jquery-1.5.1.min.js"%3E%3C/script%3E'))</script>	<script src="js/plugins.js"></script>	<script src="js/script.js"></script>	<script src="js/fadeimages.js"></script>	<!--[if lt IE 7 ]>	<script src="js/libs/dd_belatedpng.js"></script>	<script> DD_belatedPNG.fix('img, .png_bg');</script>	<![endif]--></body></html>